default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: timeframe_ha_development

test:
  <<: *default
  database: timeframe_ha_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: timeframe_ha_production
