timezone: America/Denver
birthdate: "2023-2-11"
apple_developer_team_id: bar
apple_developer_service_id: baz
apple_developer_key_id: 123
apple_developer_private_key: 456
calendars:
  -
    id: joel@hawksley.org
    letter: J