node_sonos_http_api_url: "foo"
timezone: "America/Denver"
birthdate: "2023-2-11"
latitude: "123.456"
longitude: "-45.678"
google_client_id: "baz"
google_client_secret: "baz"
google_api_key: "baz"
google_redirect_uri: "http://localhost:3000/google_callback"
home_assistant_garage_door_entity_id: "baz"
home_assistant_package_box_entity_id: "baz"
home_assistant_token: "bar"
apple_developer_team_id: "bar"
apple_developer_service_id: "baz"
apple_developer_key_id: 123
apple_developer_private_key: 456
calendars:
  -
    id: joel@hawksley.org
    letter: J
