default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: timeframe_cloud_development

test:
  <<: *default
  database: timeframe_cloud_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  databaese: timeframe_cloud_production
