default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: timeframe_development

test:
  <<: *default
  database: timeframe_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: timeframe_production
