default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  <<: *default
  database: timeframe_development

test:
  <<: *default
  database: timeframe_test

production:
  <<: *default
  database: timeframe_production