home_assistant:
  class: ScheduleJob
  queue: background
  args: ["home_assistant"]
  schedule: every 2 seconds

home_assistant_calendar:
  class: ScheduleJob
  queue: background
  args: ["home_assistant_calendar"]
  schedule: every minute

home_assistant_lightning:
  class: ScheduleJob
  queue: background
  args: ["home_assistant_lightning"]
  schedule: every minute

weather_kit:
  class: ScheduleJob
  queue: background
  args: ["weather_kit"]
  schedule: every minute

birdnet:
  class: ScheduleJob
  queue: background
  args: ["birdnet"]
  schedule: every minute

airnow:
  class: ScheduleJob
  queue: background
  args: ["airnow"]
  schedule: every minute
