default: &default
  preserve_finished_jobs: false
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        sonos:
          class: ScheduleJob
          args: [ "sonos" ]
          schedule: every 2 seconds
        home_assistant:
          class: ScheduleJob
          args: [ "home_assistant" ]
          schedule: every 10 seconds
        weather_kit:
          class: ScheduleJob
          args: [ "weather_kit" ]
          schedule: every minute
        google_calendar:
          class: ScheduleJob
          args: [ "google_calendar" ]
          schedule: every minute
        birdnet:
          class: ScheduleJob
          args: [ "birdnet" ]
          schedule: every minute
        api_response_cleanup:
          class: ApiResponseCleanupJob
          schedule: every day
  workers:
    - queues: "*"
      threads: 2
      processes: 1
      polling_interval: 1

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
