default: &default
  preserve_finished_jobs: false
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        sonos:
          class: ScheduleJob
          args: [ "sonos" ]
          schedule: every 2 seconds
        home_assistant:
          class: ScheduleJob
          args: [ "home_assistant" ]
          schedule: every 10 seconds
  workers:
    - queues: "*"
      threads: 2
      processes: 1
      polling_interval: 1

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
