name: CI

on: [push, pull_request]

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: avto-dev/markdown-lint@v1
      with:
        config: '.github/lint/markdown.json'
        args: '**/*.md'
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-build-rails-main-ruby-3.0.0-${{ hashFiles('**/Gemfile.lock') }}
    - name: Lint with standard
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec standardrb
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.1-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-build-rails-main-ruby-3.0.0-${{ hashFiles('**/Gemfile.lock') }}
    - name: Run tests
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rake db:test:prepare
        bundle exec rake
      env:
        RAILS_ENV: test
        DATABASE_URL: "postgres://postgres@localhost:5432/timeframe_test"
